### PR TITLE
Update authentic-rb to use ISS_WHITELIST and made it pipe separated

### PR DESCRIPTION
**Pull request by quantumew**
Updated per request

### CODE REVIEW

**Review by eesmith — APPROVED** [review]
👍 lgtm

**Comment by eesmith** [comment]
FYI @melhotiby

**Review by kdstew — APPROVED** [review]
LGTM!

**Comment by melhotiby** [comment]
@quantumew - so were changing from `AUTHENTIC_ISS_WHITELIST` to `ISS_WHITELIST`?

**Comment by quantumew** [comment]
@melhotiby Correct, it sounds like most of the services use a pipe delimited `ISS_WHITELIST`, so there was a request to use that for the shortcut functions here too.

**Pull request merged**
